### ISSUE TITLE
req.q missing

### ISSUE THREAD

**Issue by himoacs** [jonathonmcmurray/ws.q#4]
Hi,

I get this error when I try to run ws.q

`'reQ/req.q. OS reports: No such file or directory
  [0]  (<load>)`

The second line in ws.q is trying to load reQ/req.q but that doesn't exist.
`\l reQ/req.q`

**Comment by jonathonmcmurray** [comment]
reQ is included in the repo as a "git submodule"; essentially this means that the reQ repo is linked to this one. In order to get both, you need to use a slightly different command when cloning the repo:

```git clone --recursive https://github.com/jonathonmcmurray/ws.q.git```

Apologies for the confusion, I meant to add this instruction to the README, will try and make it more clear. 

I'm also going to be adding a new method of installation using Anaconda (some details here: http://jmcmurray.co.uk/kdb/q/package/qutil/anaconda/conda/2018/07/16/q-package-management-with-conda.html), once this is ready it will be simple to install `ws.q` and all dependencies.

Hopefully you can get the submodule working, let me know if not & I'll try and assist further

**Comment by himoacs** [comment]
Thanks, that fixed it!
